import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Practice NextJs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>Home</h1>

    </>
  )
}
