import Head from 'next/head'
import Link from 'next/link';
import HomeLayout from '../layouts/Home.layout';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Practice NextJs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>Home Page</h1>
      <h2>
        <Link href="/products" >
          see our products
        </Link>
      </h2>
    </div>
  )
}

Home.getLayout = function getLayout(page) {
  return (
      <HomeLayout>{page}</HomeLayout>
  )
}
